server:
  port : 8080
  servlet:
    context-path: /
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
spring:
  main:
    allow-bean-definition-overriding: true
  primary:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${PRIMARY_DATABASE_URL}
      port: ${DATABASE_PORT}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
  replica:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${SECONDARY_DATABASE_URL}
      port: ${DATABASE_PORT}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
  datasource:
    hikari:
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1680000
      minimumIdle: ${MINIMUM_IDLE}
      maximumPoolSize: ${MAX_POOL_SIZE}
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
  redis:
    redisson:
      config: file:/opt/apt/admin/redisson.yaml      
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        cache:
          use_second_level_cache: true
          use_query_cache: true
          use_structured_entries: true
          redisson:
            database: 7
            query:
              eviction:
                max_entries: 1000
              expiration:
                time_to_live: 240000
                max_idle_time: 180000
            entity:
              eviction:
                max_entries: 1000
              expiration:
                time_to_live: 240000
                max_idle_time: 180000
            collection:
              eviction:
                max_entries: 1000
              expiration:
                time_to_live: 240000
                max_idle_time: 180000
            config: "./redisson.yaml"
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
        generate_statistics: true
      javax:
        persistence:
          sharedCache:
            mode: ALL
  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    generate_statistics: true
hibernate:
  jdbc:
    batch_size: 20
management:
  endpoints:
    web:
      exposure:
        include: health
endpoints:
  logfile:
    enabled: true
logging:
  file: /var/log/${WEBAPP_TYPE}/${WEBAPP_TYPE}.log
  config: /opt/apt/${WEBAPP_TYPE}/logback.xml
apt:
  tracing:
    enabled: true
  web:
    recognizedHosts: '*.${HZ_DOMAIN_NAME}'
    name: WEB-APPLICATION
  env:
    name: ${ENVIRONMENT}  
aws:
  ses:
    region: ca-central-1
  mail:
    from: ${SENDER_NAME}
    replyTo: PFS.Creditors@telus.com
payment:
  application:
    name: APT
account:
  validation: true
#DB connection parameters
ssl: useSSL=true
tls:
  protocol: enabledTLSProtocols=TLSv1.2
  
